export const Urls = {
  LastMonthDstUrl: "http://localhost:8080/api/dst/last-month",
  CurrentDstUrl: "http://localhost:8080/api/dst/current-month",
  GetDstByDateUrl: "http://localhost:8080/api/dst/by-date",
  DstNowUrl: "http://localhost:8080/api/dst/now",
  Predict6hUrl: "http://localhost:8080/api/predict/6h",
  Predict1dUrl: "http://localhost:8080/api/predict/1d",
  Bz6hUrl: "http://localhost:8080/api/bz/6h",
  Bz1dUrl: "http://localhost:8080/api/bz/1d",
  Bz3dUrl: "http://localhost:8080/api/bz/3d",
  Bz7dUrl: "http://localhost:8080/api/bz/7d",
  BzNowUrl: "http://localhost:8080/api/bz/now",
  Plasma6hUrl: "http://localhost:8080/api/plasma/6h",
  Plasma1dUrl: "http://localhost:8080/api/plasma/1d",
  Plasma3dUrl: "http://localhost:8080/api/plasma/3d",
  Plasma7dUrl: "http://localhost:8080/api/plasma/7d",
  PlasmaNowUrl: "http://localhost:8080/api/plasma/now",
  Plasma2hUrl: "http://localhost:8080/api/plasma/2h",
};
